name: Setup GitVersion
description: Set up GitVersion and add it to the PATH
author: Stanley Goldman
branding:
  color: blue
  icon: tool
inputs:
  gitversion-version:
    description: Version range or exact version of GitVersion to use
  run-gitversion:
    description: Whether to run GitVersion
    default: true
runs:
  using: node12
  main: src/setup-gitversion.js
