name: Setup GitVersion
description: Set up GitVersion and add it to the PATH
author: Stanley Goldman
branding:
  color: blue
  icon: arrow-down
inputs:
  gitversion-version:
    required: true
    description: Version range or exact version of GitVersion to use
  run-gitversion:
    type: boolean
    description: Whether to run GitVersion
    default: "false"
  run-gitversion-args:
    description: Args to run with GitVersion
runs:
  using: node12
  main: src/setup-gitversion.js
