name: Test

on:
  push: {branches: master}
  pull_request: {branches: master}
  repository_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: GitVersion ${{matrix.pair.gitversion-version}}
    strategy:
      matrix:
        gitversion-version: [5.1.1]
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-setup-dotnet@v1
      - name: Use actions/setup-gitversion
        uses: ./
        with:
          gitversion-version: ${{matrix.pair.gitversion-version}}
      - name: Run GitVersion tests
        run: |-
          cd test-project
          echo "Hello World"
